Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1 (frame.clj:162)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:4599)
	at clojure.lang.Compiler.analyze(Compiler.java:4405)
	at clojure.lang.Compiler.analyze(Compiler.java:4366)
	at clojure.lang.Compiler$MapExpr.parse(Compiler.java:2649)
	at clojure.lang.Compiler.analyze(Compiler.java:4409)
	at clojure.lang.Compiler.analyze(Compiler.java:4366)
	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:372)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:4592)
	at clojure.lang.Compiler.analyze(Compiler.java:4405)
	at clojure.lang.Compiler.analyze(Compiler.java:4366)
	at clojure.lang.Compiler.eval(Compiler.java:4646)
	at clojure.lang.Compiler.load(Compiler.java:4972)
	at clojure.lang.Compiler.loadFile(Compiler.java:4939)
	at clojure.main$load_script__7405.invoke(main.clj:213)
	at clojure.main$script_opt__7442.invoke(main.clj:265)
	at clojure.main$main__7466.doInvoke(main.clj:346)
	at clojure.lang.RestFn.invoke(RestFn.java:413)
	at clojure.lang.Var.invoke(Var.java:359)
	at clojure.lang.AFn.applyToHelper(AFn.java:173)
	at clojure.lang.Var.applyTo(Var.java:476)
	at clojure.main.main(main.java:37)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at clojure.lang.PersistentArrayMap$Iter.next(PersistentArrayMap.java:256)
	at clojure.lang.Compiler$FnExpr.emitValue(Compiler.java:3345)
	at clojure.lang.Compiler$FnExpr.emitListAsObjectArray(Compiler.java:3270)
	at clojure.lang.Compiler$FnExpr.emitValue(Compiler.java:3362)
	at clojure.lang.Compiler$FnExpr.emitConstants(Compiler.java:3417)
	at clojure.lang.Compiler$FnExpr.compile(Compiler.java:3164)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3065)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:4590)
	... 20 more
